name: CI

on:
  push:
    branches: ["*"]
  merge_group:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install
        run: ARCH=ci ./install
