name: CI

on:
  - push

env:
  PYTHON_VERSION: 3.11.0

jobs:

  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml python-dotenv

      - name: Generate target conf
        run: |
          python utils/generate.py install

      - name: Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Generate target conf

  ci:
    needs: generate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Pull latest changes (including generate commit)
        run: |
          git pull origin ${{ github.ref_name }}

      - name: Install
        run: ARCH=ci ./install
