name: generate_target

on: [push]

jobs:
  generate_target:
    runs-on: ubuntu-latest
    name: generator
    strategy:
      matrix:
        python-version: [3.11.0]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml python-dotenv

      - name: Generate target conf
        run: |
          python utils/generate.py install

      - name: Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Generate target conf
